resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: docker.io/library/hello-docker-go
    newTag: latest