services:
  hello-docker-php:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
    env_file:
      - .env
    ports:
      - '8080:8080'
    
  #can be used to develop locally but run within the container
  hello-docker-php-dev:
    depends_on:
      - db
    build: .
    environment:
      MYSQL_HOST: db
    env_file:
      - .env
    ports:
      - '8081:8080'
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.2.0
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: